//! The board files that ship with this build (DESIGN.md §8.1).
//!
//! A CPS-1 board keeps its configuration in battery-backed RAM, so a set on
//! disk does not say how to run itself. Nobody has a board to read it off, and
//! everyone emulating this hardware is working from the same transcription of
//! the same research — MAME's `cps1_config_table`, keyed by the name the zip
//! is already called. So a library of those is embedded here, generated by
//! `tools/mame_to_board.zig` and looked up by the set's own name.
//!
//! It is a fallback and not a rule: a board file the user put beside their set
//! wins, because theirs is the board in front of them and this is a table.

const std = @import("std");
const board = @import("board");
const list = @import("list");

/// The board file for a set of this name, or null for a set no board here
/// covers. Names are matched without case: a set is as often `SF2.ZIP` as
/// `sf2.zip`, and MAME's own names are all lower case.
///
/// ponytail: a linear scan of a couple of hundred names, once per load.
pub fn find(name: []const u8) ?[]const u8 {
    for (list.files) |file| {
        if (std.ascii.eqlIgnoreCase(file.name, name)) return file.text;
    }
    return null;
}

// ------------------------------------------------------------------- tests

const testing = std.testing;

test "every board that ships parses" {
    for (list.files) |file| {
        var diag = board.Diag{};
        _ = board.parse(file.text, &diag) catch {
            std.debug.print("{s}.board: {s}\n", .{ file.name, diag.message() });
            return error.BadBoardFile;
        };
    }
}

test "every board that ships is under its own name, once" {
    for (list.files, 0..) |file, i| {
        try testing.expect(file.name.len != 0);
        for (list.files[i + 1 ..]) |other| {
            try testing.expect(!std.ascii.eqlIgnoreCase(file.name, other.name));
        }
    }
}

test "a set is found under the name its zip is called, whatever its case" {
    // Whichever board happens to be first: the point is the lookup, not which
    // sets the table holds today.
    const some = list.files[0].name;
    try testing.expect(find(some) != null);

    var shouted: [64]u8 = undefined;
    try testing.expectEqual(find(some), find(std.ascii.upperString(shouted[0..some.len], some)));
    try testing.expectEqual(@as(?[]const u8, null), find("a set nobody ever made"));
}
